### ISSUE TITLE
Idea: Let DJ play disc on his workstation randomly

### ISSUE THREAD

**Issue by Rivmun** [dmkenza/DiscHolder_Fabric#2]
DJ will play different music based on their mood, relationship, health etc.
Play some Epic Music when pillage has comes, and Celebrating when pillage has defeated.
Make village(rs) more alive.

**Comment by dmkenza** [comment]
Hi. Thanks for idea, but i will not develop this mod further. Sorry.
I would like to spend efforts on some new if i will have inspiration.
I have some my own ideas for new mods.

**Comment by Rivmun** [comment]
Thank you for your reply. It's a pity though, but I'm glad to see your new mods in future.
